name: Build Hello

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

Jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -f  build-essential g++ cmake
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Build project
        run: g++ main.cpp -std=c++17 -o cicd
